// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3StzAOSl-btuDdkJhwh5z-R_JwagUErQ',
    appId: '1:805095618455:web:2d795dd8011c5e1b00b6d2',
    messagingSenderId: '805095618455',
    projectId: 'vision-alliance',
    authDomain: 'vision-alliance.firebaseapp.com',
    storageBucket: 'vision-alliance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1TlNMOm0tbA5BIW99TjFuj8HXzH0fRp0',
    appId: '1:805095618455:android:d0d1c3247fb9c4f800b6d2',
    messagingSenderId: '805095618455',
    projectId: 'vision-alliance',
    storageBucket: 'vision-alliance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Dsb4ua5pzT6itxiP6_8IH0P6mTq91bQ',
    appId: '1:805095618455:ios:597b716ba05d66de00b6d2',
    messagingSenderId: '805095618455',
    projectId: 'vision-alliance',
    storageBucket: 'vision-alliance.firebasestorage.app',
    iosBundleId: 'com.example.visionAlliance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Dsb4ua5pzT6itxiP6_8IH0P6mTq91bQ',
    appId: '1:805095618455:ios:597b716ba05d66de00b6d2',
    messagingSenderId: '805095618455',
    projectId: 'vision-alliance',
    storageBucket: 'vision-alliance.firebasestorage.app',
    iosBundleId: 'com.example.visionAlliance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3StzAOSl-btuDdkJhwh5z-R_JwagUErQ',
    appId: '1:805095618455:web:da72517717e4f8db00b6d2',
    messagingSenderId: '805095618455',
    projectId: 'vision-alliance',
    authDomain: 'vision-alliance.firebaseapp.com',
    storageBucket: 'vision-alliance.firebasestorage.app',
  );
}
